// src/app/contact-agent/page.tsx
export default function ContactAgent() {
    return (
      <div style={{ textAlign: 'center', padding: '50px' }}>
        <h1>Listing Generated by AI Real Estate Copy</h1>
        <p>Contact your agent for more details.</p>
      </div>
    );
  }